 <section id="galerias">
    <div class="container">
        <center><header><h1>Galerias</h1></header></center>
        <div class="divider"></div>

<div id="contenedor">
  <form action="#">
    <div class="file-field input-field">
      <div class="btn">
        <span>Imagen 1</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </form>

<form action="#">
    <div class="file-field input-field">
      <div class="btn">
        <span>Imagen 2</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </form>



  <form action="#">
    <div class="file-field input-field">
      <div class="btn">
        <span>Imagen 3</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </form>

<form action="#">
    <div class="file-field input-field">
      <div class="btn">
        <span>Imagen 4</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </form>

    <button class="btn waves-effect waves-light" type="submit" name="action">Guardar
    <i class="material-icons right">send</i>
  </button>
</div>
</div>
    </section>